apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskpode
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flaskpode
  template:
    metadata:
      labels:
        app: flaskpode
    spec:
      containers:
      - name: flaskpode
        image: hojimat/flaskpod
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
